### ISSUE TITLE
Make an option to update the client when there's a Squirrel update

### ISSUE THREAD

**Issue by martmists** [simoniz0r/discorddownloader#3]
In the current version, whenever this appears: 
![](https://light-theme-hurts.my-ey.es/f07393.png)
I have to uninstall Discord, reinstall, and then reinject [DiscordInjections](https://github.com/DiscordInjections/DiscordInjections). I would be interested in seeing an `update` option in DiscordDownloader, as this process is extremely annoying to do manually.

**Comment by simoniz0r** [comment]
If you go through the install process again, it will automatically uninstall and reinstall the Discord version you've chosen.

There will be no option for you to keep your DiscordInjections in tact, sorry.  The Discord folder needs to be completely removed when modifications have happened to the client to avoid update loops.  Keeping files that you want to keep between installs in Discord's install directory is not a great idea.  I'd suggest you back up the files somewhere else and reinsert them after updating.

**Comment by martmists** [comment]
For me it worked by using `tar -xf discord-canary-file.tar.gz && cp -r DiscordCanary/* /opt/DiscordCanary`, no issues at all. I'll just make a fork and add it myself I guess ¯\_(ツ)_/¯

**Comment by simoniz0r** [comment]
While this may work for DiscordInjections, it will not work for any other Discord modifications.  DiscordInjections is the only Discord modification that doesn't extract the app.asar.  Extracting the app.asar causes the Discord client to go into an update loop when new updates are released if the modified files are not deleted before reinstalling.

So, if you wanna make a fork that only works with DiscordInjections, go for it, but I will be keeping discorddownloader's reinstall the way that it works now to prevent update loops with the other client modifications.

**Comment by simoniz0r** [comment]
@martmists If you're interested, I created another script, tar-pkg, that works similarly to discorddownloader, but can install any precompiled tar archive.  I've added an upgrade option to tar-pkg that allows you to overwrite the files in the install directory instead of deleting them.

https://github.com/simoniz0r/tar-pkg
