### ISSUE TITLE
mv fails due to attempting to remove /

### ISSUE THREAD

**Issue by simoniz0r** [simoniz0r/discorddownloader#4]
In #3 
`if [ "${DIR: -1}" = "/" ]; then
	DIR="${DIR::-1}"
	echo "Usage example: ./discorddownloader.sh -i ~/.Discord"
	echo "Note: Do NOT put a / at the end of the directory"
fi`
This causes mv to try and move the directory as a file instead of a directory as it should.
`mv: cannot overwrite non-directory '/home/simonizor/.Discord/Discord' with directory '/home/simonizor/Downloads/Discord/'`

Note, this error showed in this manner because 
`if [ -d /opt/DiscordCanary ]; then
	sudo rm -r /opt/DiscordCanary/
fi`
seems to have no effect.  I figured we could use `mv -f` instead of attempting to remove the directory beforehand.

**Comment by unrealcroissant** [comment]
Does this occur when using a specific flag? I didn't encounter this when testing it before the pull request. Wondering what I missed...

**Comment by simoniz0r** [comment]
This only seems to happen when the directory already exists, so I guess the real bug here is that `if [ -d /opt/DiscordCanary ]; then sudo rm -r /opt/DiscordCanary/ fi` doesn't seem to work properly.  I tried using `mv -f`, but it still throws the same error as above.  I put `sudo rm -r "$DIR"/` back in for now, and it seems to work.
